### ISSUE TITLE
Error graylog2 with elasticsearch

### ISSUE THREAD

**Issue by Tomelin** [Graylog2/graylog-ansible-role#100]
Hi, 

I installed graylog2 from playbook example, but is error:

```
TASK [elastic.elasticsearch : Install templates with auth] ***********************************************************************************************************************
skipping: [localhost] => (item=/etc/ansible/roles/elastic.elasticsearch/files/templates/basic.json)
ERROR! No file was found when using with_first_found. Use the 'skip: true' option to allow this task to be skipped if no files are found
```

```yaml
my playbook:
- hosts: server
  become: True
  vars:
    es_major_version: "5.x"
    es_instance_name: 'graylog'
    es_scripts: False
    es_templates: False
    es_version_lock: False
    es_heap_size: 1g
    es_config: {
      node.name: "graylog",
      cluster.name: "graylog",
      http.port: 9200,
      transport.tcp.port: 9300,
      network.host: 0.0.0.0,
      node.data: true,
      node.master: true,
    }

    graylog_java_install: False

    graylog_install_mongodb: True

    graylog_web_endpoint_uri: 'http://localhost:9000/api/'

    nginx_sites:
      graylog:
        - listen 80
        - server_name "{{ansible_host}}"
        - location / {
          proxy_pass http://localhost:9000/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass_request_headers on;
          proxy_connect_timeout 150;
          proxy_send_timeout 100;
          proxy_read_timeout 100;
          proxy_buffers 4 32k;
          client_max_body_size 8m;
          client_body_buffer_size 128k; }
```
