### ISSUE TITLE
Centos 7, missing package policycoreutils-python

### ISSUE THREAD

**Issue by marcin-github** [Graylog2/graylog-ansible-role#119]
```
<192.168.128.22> (0, b'', b'')
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_seport_payload_dzPIxt/__main__.py", line 110, in <module>
    import seobject
ImportError: No module named seobject

fatal: [graylog4]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ignore_selinux_state": false,
            "ports": [
                "27017"
            ],
            "proto": "tcp",
            "reload": true,
            "setype": "mongod_port_t",
            "state": "present"
        }
    },
    "msg": "Failed to import the required Python library (policycoreutils-python) on graylog4.in.sprawy.it's Python /usr/bin/python. Please read module documentation and install in the appropriate location"
}

```

**Comment by ArthurSens** [comment]
Had the same problem 

Modifing [vars/RedHat.yml](https://github.com/Graylog2/graylog-ansible-role/blob/master/vars/RedHat.yml) as seen below solved for me:

```yaml
---

graylog_server_defaults_file_path:    "/etc/sysconfig/graylog-server"
graylog_mongodb_data_path:            "/var/lib/mongo"
graylog_mongodb_package_dependencies:
  - "libselinux-python"
  - "policycoreutils-python"
graylog_java:                         "java-1.8.0-openjdk-headless.x86_64"
```
