### ISSUE TITLE
Unable to setup graylog 

### ISSUE THREAD

**Issue by arsalan993** [Graylog2/graylog-ansible-role#176]
I am running the following playbook and Graylog is not installed while it ended up installing Elasticsearch even though I have set installation of Elasticsearch to False

```
- hosts: "graylog_server"
  become: True
  vars:
    graylog_version: 4.0
    graylog_install_java: True
    graylog_install_elasticsearch: False
    graylog_install_mongodb: False
    graylog_elasticsearch_hosts: 'https://usename:password@es-logs.com:443'
    graylog_mongodb_uri: 'mongodb://username:pass@mongodb-node-01.com:27017,mongodb-node-02.com:27017,mongodb-arbiter.com:27017/graylog?replicaSet=s0'
    graylog_password_secret: " vsdvdfvdfvdfv"
    graylog_root_password_sha2: "sddsefsdgdfvgdfvdfgdfgdfgdfgdfhfgb4534545ghnghnty"
    graylog_http_bind_address: "{{ private_ip }}:9000"
    graylog_http_publish_uri: "http://{{ private_ip }}:9000/"
    graylog_http_external_uri: "http://{{ private_ip }}:9000/"
    graylog_web_listen_uri: "http://{{ private_ip }}:9000/"

  roles:
    - role: "Graylog2.graylog-ansible-role"
      tags:
        - "graylog"
```
