### ISSUE TITLE
https://galaxy.ansible.com/graylog2/graylog/ installs Graylog 1.3

### ISSUE THREAD

**Issue by klausfranken** [Graylog2/graylog-ansible-role#26]
Hi,

the version at https://galaxy.ansible.com/graylog2/graylog/ is outdated. 
It ist not the same version as https://github.com/Graylog2/graylog-ansible-role, branch 2.0.

Klaus

**Comment by mariussturm** [comment]
Hi,
thanks for the report! I renamed the 2.0 branch back to master since Galaxy can't handle other branching schemas. Should be fixed automatically when they fetch the repo again.

**Comment by jseadragon** [comment]
So, the latest ansible-galaxy package should install the 2.0 branch of this repo?

**Comment by mariussturm** [comment]
Now master since we renamed 2.0.

**Comment by jseadragon** [comment]
It appears to me that the galaxy role installed graylog 1.3... The version on the web page is `graylog-web-interface v1.3.4 (0d67a80) (Oracle Corporation 1.8.0_91 / Linux 3.16.0-69-generic) on graylog`

```
$ ansible-galaxy list
- geerlingguy.java, 1.4.0
- f500.elasticsearch, v3.0.2
- greendayonfire.mongodb, v2.0.2
- jdauphant.nginx, v2.3.1
- graylog2.graylog, 1.3.1
```

This was the configuration I used

```
---
# Install graylog from Ansible Galaxy
- hosts: graylog
  become: true
  become_method: sudo
  become_user: root
  roles:
    - graylog2.graylog
  vars:
     elasticsearch_version: '2.x'
     elasticsearch_cluster_name: 'graylog'
     elasticsearch_network_host: '0.0.0.0'
     elasticsearch_gateway_type: ''
     elasticsearch_gateway_expected_nodes: 1


     graylog_is_master: 'true'
     # generate with pwgen -s 96 1
     graylog_password_secret: <SNIP>
     # Create a password hash using: echo -n yourpassword | shasum -a 256
     graylog_root_password_sha2: <SNIP>

     # Elasticsearch message retention
     graylog_elasticsearch_max_docs_per_index: 20000000
     graylog_elasticsearch_max_number_of_indices: 20
     graylog_elasticsearch_shards: 4
     graylog_elasticsearch_replicas: 0

     # The web interface and the rest api should be accessable by the web browser
     graylog_rest_listen_uri: http://0.0.0.0:12900/
     graylog_web_listen_uri: http://0.0.0.0:9000/
     # the rest_transport_uri tells the browser how to connect to the api endpoint
     graylog_rest_transport_uri: http://127.0.0.1:12900/

```
