### ISSUE TITLE
Not running after install.

### ISSUE THREAD

**Issue by Bobspadger** [Graylog2/graylog-ansible-role#37]
I've run the ansible playbook and all has completed successfully.

I got to log into the graylog server and get the following:

Error message
Bad request
Original Request
GET http://127.0.0.1:12900/system/sessions
Status code
undefined
Full error message
Error: Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.

Any ideas?

Ubuntu 14.04.2
UFW is off.

Running on Hyper-v.

**Comment by Bobspadger** [comment]
for some additional information:

I am using the following for my playbook.yml
```
---
- hosts: kickback
  remote_user: kickback
  become: true
  become_method: sudo
  become_user: root

  vars:
    elasticsearch_version: '2.x'
    elasticsearch_cluster_name: 'graylog'
    elasticsearch_network_host: '0.0.0.0'
    elasticsearch_gateway_type: ''
    elasticsearch_gateway_expected_nodes: 1

  roles:
      - Graylog2.graylog-ansible-role
```

I have a hosts file which has:

```
[kickback]
192.168.xx.xx  ansible_user=xXXxXXxXX
```

and am running it with the following command:

`ansible-playbook playbook.yml -i "hosts" -K`
