### ISSUE TITLE
Error when (disabled) dependencies are not installed

### ISSUE THREAD

**Issue by veger** [Graylog2/graylog-ansible-role#49]
I get an error that the depend roles (ES, MongoDB, nginx) are not installed, even when I disable those functionalities using:
```
  roles:
  - role: Graylog2.graylog-ansible-role
    graylog_install_mongodb: false
    graylog_install_elasticsearch: false
    graylog_install_nginx: false
```

I would expect that by disabling them, the dependent roles do not have to be installed?
